language: julia
sudo: required
os:
  - linux
matrix:
  allow_failures:
    - julia: 0.7
julia:
  - 0.7
  - 1.0
addons:
  apt:
    packages:
    - hdf5-tools
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("BioEnergeticFoodWebs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'import Pkg; cd(Pkg.dir("BioEnergeticFoodWebs")); include(joinpath("docs", "make.jl"))'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f24a524b2166c5f2f93c
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always
