language: julia
sudo: required
os:
  - linux
# matrix:
#   allow_failures:
#     - julia: 0.7
julia:
  - 0.7
  - 1.0
  - nightly
addons:
  apt:
    update: true
    packages:
    - hdf5-tools
before_script:
  - julia -e 'using Pkg;
      Pkg.add(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.pin(PackageSpec(name="MbedTLS", version="0.6.6"));
      Pkg.add([PackageSpec(name="BinaryBuilder", rev="master"), PackageSpec(name="BinaryProvider")])'
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("BioEnergeticFoodWebs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'import Pkg; import Documenter; import BioEnergeticFoodWebs; include(joinpath("docs", "make.jl"))'
  #- julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))'
  #- julia -e 'import Pkg; cd(Pkg.dir("BioEnergeticFoodWebs")); include(joinpath("docs", "make.jl"))'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f24a524b2166c5f2f93c
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always
