site_name: BioEnergeticFoodWebs.jl
repo_url: https://github.com/PoisotLab/BioEnergeticFoodWebs.jl
site_description: Simulation of biomass dynamics on food webs
site_author: the Poisot lab

theme: material

extra:
  logo: 'befw.png'
  palette:
    primary: 'green'
    accent: 'deep orange'
  author:
    twitter: 'poisotlab'
    github: 'poisotlab'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - fenced_code
  - extra
  - tables
  - mdx_math
  - admonition

docs_dir: 'build'

pages:
  - Home: index.md
  - Manual:
    - Installation: man/installation.md
    - Generating random networks: man/random.md
    - First simulation: man/first_simulation.md
    - Extinctions: man/extinctions.md
    - Temperature dependence: man/temperature.md
    - Contributing: man/contributing.md
  - Library:
    - Public: lib/public.md
    - Internals: lib/internals.md
